"""
Regenerate the alphabetical command index on drafting/commands/index.html.

The hand-maintained index had drifted badly: 32 entries against ~74 documented
commands, while the front page claimed it listed "everything". This scrapes the
panel pages themselves, so the index cannot fall behind the reference again.

It picks up commands from two places:
  * <h3 id="..."><code class="cmd">NAME</code></h3> — a full command entry; the
    following <p> is its summary.
  * <tr><td><code class="cmd">NAME</code></td><td>...</td> — the table-only
    commands (lot text, survey text, text styles, fill bands), anchored to the
    enclosing <h2>.

Every row links to an anchor, not just the page, so clicking a command lands on
it rather than at the top of an 800-word page.

Usage (from the repo root):
    python tools/gen_index.py

Rewrites only the block between the ALPHA_START/ALPHA_END markers.
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMANDS = os.path.join(ROOT, "drafting", "commands")
INDEX = os.path.join(COMMANDS, "index.html")

START = "<!-- ALPHA_START — generated by tools/gen_index.py, do not hand-edit -->"
END = "<!-- ALPHA_END -->"

# Directory name -> label used in the "Where" column.
PANELS = [
    ("cadastre", "Cadastre"),
    ("survey", "Survey"),
    ("text", "Text &amp; Labels"),
    ("annotation", "Annotation"),
    ("sheeting", "Sheeting"),
    ("dimensions", "Dimensions"),
    ("topography", "Topography"),
    ("utilities", "Utilities"),
]

# Numbered families listed as one row rather than eleven near-identical ones.
FAMILIES = [
    (re.compile(r"^FILL(\d+)$"), "FILL1</code>–<code class=\"cmd\">FILL11"),
]

# A few summaries only make sense next to the command above them, or sit in a
# table whose second column is a style name rather than a description. The
# index has no such context, so those are written out here.
OVERRIDES = {
    "ADJBDY": "Puts adjoining lot boundaries on the adjoining-boundary layer",
    "FILL1": "Earthworks depth-band hatching, one command per band",
    "THINTXT": "Place or restyle text in the THIN LABEL style",
    "SMALLTXT": "Place or restyle text in the SMALL LABEL style",
    "MEDTXT": "Place or restyle text in the MEDIUM LABEL style",
    "LRGTXT": "Place or restyle text in the LARGE LABEL style",
}

TAGS = re.compile(r"<[^>]+>")
WS = re.compile(r"\s+")


def text_of(html):
    """Strip tags and collapse whitespace."""
    return WS.sub(" ", TAGS.sub("", html)).strip()


def summarise(raw):
    """First sentence, trimmed — the index column is a reminder, not the doc."""
    s = text_of(raw)
    s = re.split(r"(?<=[a-z0-9\)])\.\s+", s)[0]
    s = s.rstrip(".").strip()
    if len(s) > 78:
        s = s[:75].rsplit(" ", 1)[0] + "…"
    return s[:1].upper() + s[1:] if s else s


def scrape(slug, label):
    """Every command documented on one panel page."""
    path = os.path.join(COMMANDS, slug, "index.html")
    with io.open(path, encoding="utf-8") as fh:
        page = fh.read()

    found = []
    section = ""  # most recent <h2 id>, for anchoring table-only commands

    # One pass in document order so table rows inherit the right <h2>.
    pattern = re.compile(
        r'<h2 id="(?P<h2>[^"]+)"'
        r'|<h3 id="(?P<h3>[^"]+)"><code class="cmd">(?P<name>[^<]+)</code></h3>\s*<p>(?P<summary>.*?)</p>'
        r'|<tr><td><code class="cmd">(?P<row>[^<]+)</code></td><td>(?P<cell>.*?)</td>',
        re.S,
    )
    for m in pattern.finditer(page):
        if m.group("h2"):
            section = m.group("h2")
        elif m.group("h3"):
            name = m.group("name").strip()
            found.append((name, m.group("h3"),
                          OVERRIDES.get(name) or summarise(m.group("summary")),
                          slug, label))
        elif m.group("row"):
            name = m.group("row").strip()
            found.append((name, section,
                          OVERRIDES.get(name) or summarise(m.group("cell")),
                          slug, label))
    return found


def collapse(rows):
    """Fold numbered families (FILL1…FILL11) into a single entry."""
    out, seen = [], set()
    for name, anchor, summary, slug, label in rows:
        for pat, display in FAMILIES:
            if pat.match(name):
                key = (pat.pattern, slug)
                if key in seen:
                    break
                seen.add(key)
                out.append((pat.match(name).re.pattern, display, anchor,
                            summary, slug, label))
                break
        else:
            out.append((name, name, anchor, summary, slug, label))
    return out


def sort_key(entry):
    """Alphabetical on the first command name, digits ordered numerically."""
    name = entry[1].split("<")[0]
    m = re.match(r"^([A-Z]+)(\d*)", name)
    return (m.group(1), int(m.group(2) or 0)) if m else (name, 0)


def render(rows):
    lines = [START, '    <div class="table-wrap">', "    <table id=\"cmdIndex\">",
             "      <thead><tr><th>Command</th><th>Does</th><th>Where</th></tr></thead>",
             "      <tbody>"]
    for _, display, anchor, summary, slug, label in rows:
        names = " / ".join(
            '<code class="cmd">{0}</code>'.format(n.strip())
            for n in display.split(" / ")
        )
        lines.append(
            '        <tr><td>{0}</td><td>{1}</td>'
            '<td><a href="{2}/#{3}">{4}</a></td></tr>'.format(
                names, summary, slug, anchor, label)
        )
    lines += ["      </tbody>", "    </table>", "    </div>", END]
    return "\n".join(lines)


def main():
    rows = []
    for slug, label in PANELS:
        rows.extend(scrape(slug, label))
    rows = sorted(collapse(rows), key=sort_key)

    with io.open(INDEX, encoding="utf-8") as fh:
        page = fh.read()
    if START not in page or END not in page:
        sys.exit("markers not found in %s — add them before regenerating" % INDEX)

    head, rest = page.split(START, 1)
    _, tail = rest.split(END, 1)
    with io.open(INDEX, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(head + render(rows) + tail)

    print("%d commands indexed across %d panels" % (len(rows), len(PANELS)))


if __name__ == "__main__":
    main()
